name: cave
repository: https://github.com/GDG-W/cave

packages:
  - packages/**

scripts:
  lint:all:
    steps:
      - analyze
      - format
    description: Run all static analysis checks.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  generate:
    run: melos exec -c 1 --depends-on="build_runner" -- "dart run build_runner build -d"
    description: Build all generated files.