name: Volunteer App CI

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'packages/volunteerapp/**'
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog for this release'
        required: true
      build-version:
        description: 'Version number for the release'
        required: true
      build-number:
        description: 'Build number for the release'
        required: true

jobs:
  check-formatting:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: volunteerapp

  android-build:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      package-name: volunteerapp
      android-build: true
      changelog: ${{ github.event.inputs.changelog }}
      build-number: ${{ github.event.inputs.build-number }}
      build-version: ${{ github.event.inputs.build-version }}
    secrets:
      CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

  # ios-build:
  #   if: github.event_name == 'workflow_dispatch'
  #   uses: ./.github/workflows/shared-workflow.yaml
  #   with:
  #     package-name: volunteerapp
  #     ios-build: true
  #     changelog: ${{ github.event.inputs.changelog }}
